- name: Add Zabbix Repo
  ansible.builtin.yum_repository:
    name: zabbix
    description: Zabbix repository
    baseurl: https://repo.zabbix.com/zabbix/6.2/rhel/8/$basearch/
  gpgcheck: noe

- name: Update the system
  ansible.buildin.yum:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  become: true

- name: Install Zabbix Server Frontend
  ansible.buildin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - zabbix-server-mysql
    - zabbix-sql-scripts
    - zabbix-selinux-policy
    - zabbix-agent
    - zabbix-apache-conf
    - zabbix-web-mysql
  become: true

      #  - name: Configure Zabbix Frontend
    #    ansible.builtin.copy:
      #      src: /etc/zabbix/nginx.conf
        #      dest: /etc/nginx/sites-available/nginx.conf
        #      backup: yes
        #      remote_src: yes
        #      force: yes
        #    become: true

      #  - name: Link Config file
    #    ansible.builtin.file:
      #     src: /etc/nginx/sites-available/nginx.conf
       #     dest: /etc/nginx/sites-enabled/nginx.conf
       #     state: link
       #    become: true

      #  - name: Delete Default Config file
    #    ansible.builtin.file:
      #      path: /etc/nginx/sites-enabled/default
        #      state: absent
        #    become: true

- name: Change Timezone
  lineinfile:
    dest: /etc/zabbix/php-fpm.conf
    regexp: 'Europe/Riga'
    line: 'php_value[date.timezone] = Asia/Yangon'
    state: present
  become: true
