- name: Understanding precedence of variable
  hosts: all
  become: yes
    #  vars: 
    #    USRNM: luminaung
    #    COMM:  This is the valriable user name
  tasks:
    - name: create a user
      user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: USROUT

    - debug:
        var: USROUT.name
    
    - debug:
        var: USROUT.comment
