- name: Provisioning Server
  hosts: test
  become: yes
  tasks :
    - name: Install zabbix repo on Centos
      ansible.builtin.yum_repository:
        name: zabbix
        description: zabbix repo
        baseurl: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
    
    - name: add mariadb 10.5 repository
      become: true
      template:
        src: mariadb.repo
        dest: /etc/yum.repos.d/mariadb.repo

  - name: Start and Enable the Database Server 
    service:
      name: chronyd
      state: started
    service:
      name: chronyd
      state: enabled

    - name: Install Zabbix server and agent packages and mariadb
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-mysql
        - zabbix-agent
        - mariadb
        - mariadb-server


