---
- name: Install Zabbix Server 6.0
  hosts: test
  become: true
    #  - name: Install Zabbix repositor
    #    dnf_repository:
    #      name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
    #      state: present

  - name: add mariadb 10.5 repository
    become: true
    template:
      src: mariadb.repo
      dest: /var/yum.repo.d/mariadb.repo

  - name: Install Zabbix server , agent and mariadb packages
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - zabbix-server-mysql
      - zabbix-agent
      - mariadb
      - mariadb-server

  - name: Install Zabbix web frontend packages
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - zabbix-web-mysql
      - httpd
      - php
      - php-mysqlnd

  - name: start and enable mairadb server
    service: 
     name: mariadb
     state: started

  - name: Configure MariaDB
    mysql_db:
      name: zabbix
      collation: utf8_bin
      encoding: utf8
      state: present
    become: true

  - name: Create Zabbix database user
    mysql_user:
      name: zabbix
      password: "password"
      priv: 'zabbix.*:ALL'
      host: localhost
      state: present
    become: true

  - name: Configure Zabbix server
    become: true
    template:
      src: templates/zabbix_server.conf.j2
      dest: /etc/zabbix/zabbix_server.conf
    notify:
      - restart zabbix-server

  - name: Configure Zabbix web frontend
    become: true
    template:
      src: templates/zabbix.conf.j2
      dest: /etc/httpd/conf.d/zabbix.conf
    notify:
      - restart httpd

  handlers:
  - name: restart zabbix-server
    service:
      name: zabbix-server
      state: restarted

  - name: restart httpd
    service:
      name: httpd
      state: restarted
